#!/bin/bash
#
# A Proxmox hook script to transition a data URL from a VM image into a file that
# is deployed as part of a VM configuration
#

# see
# - /usr/share/pve-docs/examples/guest-example-hookscript.pl
#
set -e

VM_ID=$1
PHASE=$2

function configure()
{
        local VM_ID=$1

        DATA_URL_BASE64=$(/usr/sbin/qm config ${VM_ID} | sed -ne 's/^description: data:application\/vnd.coreos.ignition+json[^,]*;base64[^,]*,\(.*\)/\1/gp')
        if [ -n "${DATA_URLi_BASE64}" ] ; then
                echo "Write me: $(echo ${DATA_URL_BASE64} | base64 -d )"
        else
                echo "Data URL configuration not present"
        fi
}



if [ "${PHASE}" = 'pre-start' ]; then
        configure $1
elif [ "${PHASE}" = 'post-start' ]; then
  # nothing to do
elif [ "${PHASE}" = 'pre-stop' ]; then
  # nothing to do
elif [ "${PHASE}" = 'post-stop' ]; then
  # nothing to do
else
        echo "Invalid hook script phase ${PHASE}"
        exit 1
fi

